from pathlib import Path
p=Path('betting.html')
s=p.read_text(encoding='utf-8')
old='''async function loadMyBets(){const box=$("#myBets");box.innerHTML='<div class="muted">טוען את ההימורים שלך...</div>';const {data,error}=await db.from("bets").select("id,bet_code,created_at,player_name,stake,total_odd,potential_win,picks,payment_status,result_status,paid_at,paid_by").neq("result_status","cancelled").order("created_at",{ascending:false}).limit(100);if(error){box.innerHTML='<div class="statusMsg error">לא ניתן לטעון את ההימורים: '+esc(error.message)+'</div>';return}const byId=new Map((data||[]).filter(b=>b.result_status!=="cancelled").map(b=>[b.id,b]));const renderNow=()=>renderMyBets([...byId.values()].filter(b=>b.result_status!=="cancelled").sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)));renderNow();const existingCodes=new Set([...byId.values()].map(b=>String(b.bet_code||'').toUpperCase()));const savedCodes=getSavedTicketCodes(),missingCodes=savedCodes.filter(code=>!existingCodes.has(String(code).toUpperCase()));if(!missingCodes.length)return;const results=await Promise.allSettled(missingCodes.map(code=>fetchImportedBet(code)));let changed=false;const hiddenCodes=new Set();results.forEach((r,i)=>{if(r.status!=="fulfilled"||!r.value)return;const b=r.value;if(b.result_status==="cancelled"){hiddenCodes.add(missingCodes[i]);return}byId.set(b.id,b);changed=true});if(hiddenCodes.size)localStorage.setItem("redball_saved_ticket_codes",JSON.stringify(savedCodes.filter(code=>!hiddenCodes.has(code))));if(changed)renderNow()}'''
new='''async function loadMyBets(){const box=$("#myBets");box.innerHTML='<div class="muted">טוען את ההימורים שלך...</div>';const {data,error}=await db.from("bets").select("id,bet_code,created_at,player_name,stake,total_odd,potential_win,picks,payment_status,result_status,paid_at,paid_by").neq("result_status","cancelled").order("created_at",{ascending:false}).limit(100);if(error){box.innerHTML='<div class="statusMsg error">לא ניתן לטעון את ההימורים: '+esc(error.message)+'</div>';return}const byId=new Map((data||[]).filter(b=>b.result_status!=="cancelled").map(b=>[b.id,b]));const renderNow=()=>renderMyBets([...byId.values()].filter(b=>b.result_status!=="cancelled").sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)));renderNow();const existingCodes=new Set([...byId.values()].map(b=>String(b.bet_code||'').toUpperCase()));const savedCodes=getSavedTicketCodes(),missingCodes=savedCodes.filter(code=>!existingCodes.has(String(code).toUpperCase()));if(!missingCodes.length)return;const batch=missingCodes.slice(0,3),results=await Promise.allSettled(batch.map(code=>fetchImportedBet(code)));let changed=false;const removeCodes=new Set();results.forEach((r,i)=>{if(r.status!=="fulfilled")return;const b=r.value;if(!b||b.result_status==="cancelled"){removeCodes.add(batch[i]);return}byId.set(b.id,b);changed=true});if(removeCodes.size)localStorage.setItem("redball_saved_ticket_codes",JSON.stringify(savedCodes.filter(code=>!removeCodes.has(code))));if(changed)renderNow()}'''
if old not in s: raise SystemExit('loadMyBets anchor not found')
s=s.replace(old,new,1)
old2='''}catch(e){msg.textContent="לא ניתן לבצע את החיפוש כרגע.";msg.className="statusMsg error searchMsg"}finally{btn.disabled=false;btn.textContent="🔎 חפש"}}'''
new2='''}catch(e){msg.textContent=e&&e.message?e.message:"לא ניתן לבצע את החיפוש כרגע.";msg.className="statusMsg error searchMsg"}finally{btn.disabled=false;btn.textContent="🔎 חפש"}}'''
if old2 not in s: raise SystemExit('searchTicket error anchor not found')
s=s.replace(old2,new2,1)
p.write_text(s,encoding='utf-8')
print('patched')
